version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - laravel

  php:
    image: php:7.2-fpm
    container_name: php-fpm
    volumes:
      - ./src:/var/www
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
