version: "3"

services:
  openresty:
    image: openresty/openresty:latest
    container_name: openresty
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/local/src
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/usr/local/openresty/nginx/logs
    restart: always
    depends_on:
      - fpm
    networks:
      - unity

  fpm:
    # image: phrc/php72_fpm:latest
    build: .
    container_name: php-fpm
    volumes:
      - ./src:/usr/local/src
    environment:
      - PHP_ENABLE_XDEBUG=1
    restart: always
    depends_on:
      - mysql
    networks:
      - unity

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password      
    restart: always
    networks:
      - unity

networks:
  unity:
    driver: bridge
